# Generated by Django 3.1.5 on 2021-01-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210112_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-batch', 'solve']},
        ),
    ]
